### ISSUE TITLE
does not prefix selectors inside @media queries

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-plugin-prefix-selectors#1]
Moved from https://github.com/reworkcss/rework/issues/112

Example:

``` javascript
rework.prefixSelectors('.hack')
```

source:

``` css
@media print {
  .visible-print {
    display: block !important;
  }
}
```

expected:

``` css
@media print {
  .hack .visible-print {
    display: block !important;
  }
}
```

result: untouched source, without `.hack` prefix.

---

Follow up comment from @andi-neck:

I didn't find a way to fix it without breaking the existing visit implementation. That's why I modified [rework-visit](https://github.com/visionmedia/rework-visit) into a [rework-walk](https://github.com/intesso/rework-walk) plugin (now I think it's a stupid name :-) that calls the callback function with rule/keyframe instead of their declarations, and implemented [rework-prefix-all-selectors](https://github.com/intesso/rework-prefix-all-selectors) on top of it (even worse naming...).

Any Ideas how to fix it with the existing rework-visit implementation, without breaking other stuff?

---

Follow up comment from @ericf

I've created [rework-mutate-selectors](https://github.com/ericf/rework-mutate-selectors) which does selector prefixing and find/replace. I also created a [grunt-css-selectors](https://github.com/ericf/grunt-css-selectors) which is a Grunt wrapper around this.

I think `rework-mutate-selectors` can serve this role, and it's already has some [decent usage](https://www.npmjs.org/package/rework-mutate-selectors#package).
